app: fiap-hackathon-emailreport
service: fiap-hackathon-emailreport
frameworkVersion: "3"
useDotenv: true

custom:
  serverless-offline:
    httpPort: 3001
  # API_GATEWAY_API_ID: ${ssm:/fiap-tech/api_gateway/api_id}
  SQS_NOTIFICATION: ${ssm:/fiap-tech/sqs/arn}
  ETHEREAL_MAIL_USER: ${ssm:/fiap-tech/lambda/mailuser}
  ETHEREAL_MAIL_PASSW: ${ssm:/fiap-tech/lambda/mailpassw}
  LAB_ROLE: ${ssm:/fiap-tech/lab_role}

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 30
  stage: dev
  iam:
    role: ${self:custom.LAB_ROLE}
  environment:
    ETHEREAL_MAIL_USER: ${self:custom.ETHEREAL_MAIL_USER}
    ETHEREAL_MAIL_PASSW: ${self:custom.ETHEREAL_MAIL_PASSW}

# resources:
#   Resources:
#     NotificationQueue:
#       Type: AWS::SQS::Queue
#       Properties:
#         QueueName: ${env:SQS_NOTIFICATION}
#         SqsManagedSseEnabled: false

functions:
  sendReport:
    handler: src/functions/sendReport.handler
    events:	
      - sqs: ${ssm:/fiap-tech/sqs/arn}

package:
  excludeDevDependencies: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript